export default {
  login: 'Login',
  register: 'Register',
  buttonText: 'Next',
  emailPlaceholder: 'Email....',
  noAccount: "You don't have any account please ",
  footerText: 'register',
  already: 'If you have account, please ',
  footerTextre: 'login',
  language: 'Language',
  english: 'English',
  myanmar: 'Myanmar',
  close: 'Hide',
  security: 'Security',
  pwdPlaceholder: 'Password....',
  conpwdPlaceholder: 'Confirm Password....',
  remember: 'Remember Password',
  email: 'Email:',
  dashboardtitle: 'Dashboard',
  about: `User's Info`,
  logout: 'Logout',
};
