export default {
  login: 'အကောင့်ဝင်ရန်',
  register: 'အကောင့်ဖွင့်ရန်',
  buttonText: 'နောက်သို့',
  emailPlaceholder: 'အီးမေးလ်....',
  noAccount: 'အကောင့်မရှိပါက ',
  footerText: 'အကောင့်ဖွင့်ပါ',
  already: 'အကောင့်ရှိလျှင် ',
  footerTextre: 'အကောင့်ဝင်ပါ',
  language: 'ဘာသာစကား',
  english: 'အင်္ဂလိပ်',
  myanmar: 'မြန်မာ',
  close: 'ပိတ်ပါ',
  security: 'လုံခြုံရေး',
  pwdPlaceholder: 'စကားဝှက်....',
  conpwdPlaceholder: 'ဒုတိယစကားဝှက်....',
  remember: 'စကားဝှက်ကို မှတ်ထားပါ',
  email: 'အီးမေးလ်:',
  dashboardtitle: 'ဒက်ရှ်ဘုတ်',
  about: 'အသုံးပြုသူ၏အချက်အလက်',
  logout: 'လော့အောက်',
};
